/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package hospitalmanagement;
import java.awt.*;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.*;

/**
 *
 * @author Faisal
 */
public class LoginPage extends javax.swing.JFrame {

    /**
     * Creates new form LoginPage
     */
    public LoginPage() {
        initComponents();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel(){

            public void paintComponent(Graphics g)
            {
                ImageIcon ii = new ImageIcon("login.png");
                Image i = ii.getImage();

                g.drawImage(i, 0, 0, this.getSize().width, this.getSize().height, this);
            }

        };
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        user = new javax.swing.JTextField();
        pw = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lock = new javax.swing.JLabel();
        lbtn = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ti = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 335, 230, 31));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 390, 231, 31));

        user.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 333, 230, 35));

        pw.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(pw, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 390, 230, 31));

        jLabel4.setFont(new java.awt.Font("Tahoma", 2, 17)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("USER NAME:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 335, 100, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 2, 17)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("PASSWORD:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 390, 95, 30));

        lock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalmanagement/Lock.png"))); // NOI18N
        jPanel1.add(lock, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 300, 110, 160));

        lbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lbtnMouseReleased(evt);
            }
        });
        jPanel1.add(lbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 440, 80, 36));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalmanagement/form.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 540, 380));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalmanagement/logo m.PNG"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 160, 180));
        jPanel1.add(ti, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 90, 30));

        jLabel7.setBackground(new java.awt.Color(0, 102, 255));
        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("COPYRIGHT BT FAISAL.ALI.APTECHNN@GMAIL.COM");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 574, 600, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 596, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbtnMouseEntered
        // TODO add your handling code here:
        ImageIcon ii = new ImageIcon(getClass().getResource("form btn.png"));
        lbtn.setIcon(ii);
    }//GEN-LAST:event_lbtnMouseEntered

    private void lbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbtnMouseExited
        // TODO add your handling code here:
        ImageIcon ii = new ImageIcon(getClass().getResource(""));
        lbtn.setIcon(ii);
    }//GEN-LAST:event_lbtnMouseExited

    private void lbtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbtnMousePressed
        // TODO add your handling code here:
        ImageIcon ii = new ImageIcon(getClass().getResource("form btn2.png"));
        lbtn.setIcon(ii);
    }//GEN-LAST:event_lbtnMousePressed

    private void lbtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbtnMouseReleased
        // TODO add your handling code here:
        ImageIcon ii = new ImageIcon(getClass().getResource(""));
        lbtn.setIcon(ii);
    }//GEN-LAST:event_lbtnMouseReleased

    private void lbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbtnMouseClicked
        // TODO add your handling code here:
        String id , pass;
        id = user.getText();
        pass = pw.getText();
        
        if(id.equalsIgnoreCase("admin") && pass.equalsIgnoreCase("faisal"))
        {
            ImageIcon ii = new ImageIcon(getClass().getResource("open lock.png"));
            lock.setIcon(ii);
           
            JOptionPane.showMessageDialog(this, "Sucessfull login");
            
            this.setVisible(false);

            new Options().setVisible(true);
            
        }
        else if(id.equalsIgnoreCase("admin") && !pass.equalsIgnoreCase("faisal"))
        {

            JOptionPane.showMessageDialog(this, "Your Password is Wrong");
        }
        else if(!id.equalsIgnoreCase("admin") && pass.equalsIgnoreCase("faisal"))
        {
            JOptionPane.showMessageDialog(this, "Your UserName is Wrong");
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Your UserName and Password is Wrong");
        }
    }//GEN-LAST:event_lbtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                /*if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }*/
                UIManager.setLookAndFeel("com.jtattoo.plaf.aero.AeroLookAndFeel");
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbtn;
    private javax.swing.JLabel lock;
    private javax.swing.JPasswordField pw;
    private javax.swing.JLabel ti;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
}
