/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package hospitalmanagement;

import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author Faisal
 */
public class Options extends javax.swing.JFrame {
    private JPanel jPanel1;
    int run = 0;

    /**
     * Creates new form Options
     */
    public Options() {
        initComponents();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
              new Thread() 
        {
            public void run()
            {
                while(run == 0)
                {
                    int h , m , s, a_p , d ,mm , y;
                    Calendar abc = new GregorianCalendar();
        
                    h = abc.get(Calendar.HOUR);
                    // here we can write both calender and abc
                    m = abc.get(abc.MINUTE);
                    s = abc.get(abc.SECOND);
                    a_p = abc.get(abc.AM_PM); // AM = 0 and PM = 1 in int
                    d = abc.get(abc.DATE);
                    mm = abc.get(Calendar.MONTH);
                    y = abc.get(abc.YEAR);
                    
                    String d_n = "";
                    if(a_p==1)
                    {
                        d_n = "PM";
                    }
                    else
                    {
                        d_n = "AM";
                    }
                    
                    String date = d + "/" + mm + "/" + y;
                    String time = h + ":" + m + ":" + s + " " + d_n;
                    clock.setText(time);
                    cal.setText(date);
                    
                }
            }  
        }.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpo = jPanel1 = new javax.swing.JPanel(){

            public void paintComponent(Graphics g)
            {
                ImageIcon iio = new ImageIcon("m bg.jpg");
                Image io = iio.getImage();

                g.drawImage(io, 0, 0, this.getSize().width, this.getSize().height, this);
            }

        };
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        a = new javax.swing.JButton();
        b = new javax.swing.JButton();
        d = new javax.swing.JButton();
        c = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        clock = new javax.swing.JLabel();
        cal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalmanagement/logo m.PNG"))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(180, 226, 234));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, java.awt.Color.white), "Options Panel", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Algerian", 1, 36), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.setName(""); // NOI18N
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        a.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalmanagement/d btn.jpg"))); // NOI18N
        a.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                aMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                aMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                aMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                aMouseReleased(evt);
            }
        });
        jPanel2.add(a, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 105, 170, 60));

        b.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalmanagement/p btn.jpg"))); // NOI18N
        b.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bMouseReleased(evt);
            }
        });
        jPanel2.add(b, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 110, 165, 55));

        d.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalmanagement/ro btn.jpg"))); // NOI18N
        d.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                dMouseReleased(evt);
            }
        });
        jPanel2.add(d, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 290, 165, 55));

        c.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalmanagement/s btn.jpg"))); // NOI18N
        c.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cMouseReleased(evt);
            }
        });
        jPanel2.add(c, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 165, 55));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalmanagement/doctor icon.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 130, 130));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalmanagement/patient.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, -1, 130));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalmanagement/or.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, 120, 130));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalmanagement/staff icon.png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 140, 130));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Stencil Std", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 255));
        jButton1.setText("Log Out");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        clock.setFont(new java.awt.Font("Digital-7", 1, 24)); // NOI18N
        clock.setForeground(new java.awt.Color(255, 255, 255));

        cal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cal.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jpoLayout = new javax.swing.GroupLayout(jpo);
        jpo.setLayout(jpoLayout);
        jpoLayout.setHorizontalGroup(
            jpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpoLayout.createSequentialGroup()
                .addContainerGap(158, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 786, Short.MAX_VALUE)
                .addGap(28, 28, 28)
                .addGroup(jpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cal, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                    .addComponent(clock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpoLayout.setVerticalGroup(
            jpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpoLayout.createSequentialGroup()
                .addGroup(jpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpoLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpoLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
                        .addContainerGap(22, Short.MAX_VALUE))
                    .addGroup(jpoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(clock, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cal, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void aMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aMouseEntered
        // TODO add your handling code here:
        
        ImageIcon ii = new ImageIcon(getClass().getResource("d btn2.jpg"));
        a.setIcon(ii);
    }//GEN-LAST:event_aMouseEntered

    private void aMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aMouseExited
        // TODO add your handling code here:
        ImageIcon ii = new ImageIcon(getClass().getResource("d btn.jpg"));
        a.setIcon(ii);
    }//GEN-LAST:event_aMouseExited

    private void aMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aMousePressed
        // TODO add your handling code here:
        ImageIcon ii = new ImageIcon(getClass().getResource("d btn 3.jpg"));
        a.setIcon(ii);
    }//GEN-LAST:event_aMousePressed

    private void aMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aMouseReleased
        // TODO add your handling code here:
         ImageIcon ii = new ImageIcon(getClass().getResource("d btn.jpg"));
        a.setIcon(ii);
    }//GEN-LAST:event_aMouseReleased

    private void bMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bMouseEntered
        // TODO add your handling code here:
        ImageIcon ii = new ImageIcon(getClass().getResource("p btn 2.jpg"));
        b.setIcon(ii);
    }//GEN-LAST:event_bMouseEntered

    private void bMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bMouseExited
        // TODO add your handling code here:
        ImageIcon ii = new ImageIcon(getClass().getResource("p btn.jpg"));
        b.setIcon(ii);
    }//GEN-LAST:event_bMouseExited

    private void bMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bMousePressed
        // TODO add your handling code here:
        ImageIcon ii = new ImageIcon(getClass().getResource("p btn 3.jpg"));
        b.setIcon(ii);
    }//GEN-LAST:event_bMousePressed

    private void bMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bMouseReleased
        // TODO add your handling code here:
        ImageIcon ii = new ImageIcon(getClass().getResource("p btn.jpg"));
        b.setIcon(ii);
    }//GEN-LAST:event_bMouseReleased

    private void aMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aMouseClicked
        // TODO add your handling code here:
        this.hide();
        new Doctor().show();
    }//GEN-LAST:event_aMouseClicked

    private void bMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bMouseClicked
        // TODO add your handling code here:
        this.hide();
        new Patient().show();
    }//GEN-LAST:event_bMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        this.hide();
        new LoginPage().show();
    }//GEN-LAST:event_jButton1MouseClicked

    private void cMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cMouseClicked
        // TODO add your handling code here:
        new Staff().show();
        this.hide();
    }//GEN-LAST:event_cMouseClicked

    private void dMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dMouseClicked
        // TODO add your handling code here:
        new RoomsAndBeds().show();
        this.hide();
    }//GEN-LAST:event_dMouseClicked

    private void cMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cMouseEntered
        // TODO add your handling code here:
         ImageIcon ii = new ImageIcon(getClass().getResource("s btn 2.jpg"));
        c.setIcon(ii);
    }//GEN-LAST:event_cMouseEntered

    private void cMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cMouseExited
        // TODO add your handling code here:
         ImageIcon ii = new ImageIcon(getClass().getResource("s btn.jpg"));
        c.setIcon(ii);
    }//GEN-LAST:event_cMouseExited

    private void cMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cMousePressed
        // TODO add your handling code here:
         ImageIcon ii = new ImageIcon(getClass().getResource("s btn3.jpg"));
        c.setIcon(ii);
    }//GEN-LAST:event_cMousePressed

    private void cMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cMouseReleased
        // TODO add your handling code here:
         ImageIcon ii = new ImageIcon(getClass().getResource("s btn.jpg"));
        c.setIcon(ii);
    }//GEN-LAST:event_cMouseReleased

    private void dMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dMouseEntered
        // TODO add your handling code here:
         ImageIcon ii = new ImageIcon(getClass().getResource("ro btn2.jpg"));
        d.setIcon(ii);
    }//GEN-LAST:event_dMouseEntered

    private void dMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dMouseExited
        // TODO add your handling code here:
         ImageIcon ii = new ImageIcon(getClass().getResource("ro btn.jpg"));
        d.setIcon(ii);
    }//GEN-LAST:event_dMouseExited

    private void dMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dMousePressed
        // TODO add your handling code here:
         ImageIcon ii = new ImageIcon(getClass().getResource("ro btn3.jpg"));
        d.setIcon(ii);
    }//GEN-LAST:event_dMousePressed

    private void dMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dMouseReleased
        // TODO add your handling code here:
         ImageIcon ii = new ImageIcon(getClass().getResource("ro btn.jpg"));
        d.setIcon(ii);
    }//GEN-LAST:event_dMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Options.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Options.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Options.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Options.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try
                {
                    Thread.sleep(4000);
                }
                catch(Exception e)
                {
                    System.out.println(e);
                }
                new Options().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton a;
    private javax.swing.JButton b;
    private javax.swing.JButton c;
    private javax.swing.JLabel cal;
    private javax.swing.JLabel clock;
    private javax.swing.JButton d;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jpo;
    // End of variables declaration//GEN-END:variables
}
