/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package hospitalmanagement;

import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Faisal
 */
public class SearchStaff extends javax.swing.JFrame {
public static String C_lass = "com.microsoft.sqlserver.jdbc.SQLServerDriver";
public static String C_lass1 = "jdbc:sqlserver://localhost:1433;databaseName=Management;username=faisal;password=kiru";
/**
     * Creates new form SearchStaff
     */
    public SearchStaff() {
        initComponents();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ssh2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ssjtable2 = new javax.swing.JTable();
        ssd = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        ssid = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        ssjtable1 = new javax.swing.JTable();
        ssh1 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        ssh2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        ssh2.setForeground(new java.awt.Color(51, 51, 255));
        ssh2.setText("ALL RECORD OF NURSES / WARD BOYS:");

        ssjtable2.setBackground(new java.awt.Color(51, 102, 255));
        ssjtable2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ssjtable2.setForeground(new java.awt.Color(255, 255, 255));
        ssjtable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "FIRST NAME", "LAST NAME", "JOINING", "AGE", "GENDER", "PRESENT ADDRESS", "EMAIL ADD", "CONTACT", "DESINATION", "TIMING"
            }
        ));
        jScrollPane2.setViewportView(ssjtable2);

        ssd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ssd.setForeground(new java.awt.Color(0, 102, 255));
        ssd.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "NURSE", "WARD BOY" }));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("SEARCH BY ID:");

        ssid.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 51, 255));
        jButton2.setText("SEARCH");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        ssjtable1.setBackground(new java.awt.Color(51, 102, 255));
        ssjtable1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 102, 255)));
        ssjtable1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ssjtable1.setForeground(new java.awt.Color(255, 255, 255));
        ssjtable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "FIRST NAME", "LAST NAME", "JOINING", "AGE", "GENDER", "PRESENT ADDRESS", "EMAIL ADD", "CONTACT", "DESINATION", "TIMING"
            }
        ));
        jScrollPane3.setViewportView(ssjtable1);

        ssh1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        ssh1.setForeground(new java.awt.Color(51, 51, 255));
        ssh1.setText("SINGLE RECORD OF NURSE / WARD BOY:");

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setFont(new java.awt.Font("Stencil Std", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(51, 51, 255));
        jButton5.setText("Log Out");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addComponent(jScrollPane3)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ssh2)
                            .addComponent(ssh1))
                        .addGap(29, 480, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ssid, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ssd, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ssid, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ssd, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(ssh1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ssh2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        
    
        if(ssd.getSelectedIndex()==0)
        {
        try{

              Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");

              Connection con = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=Management;username=faisal;password=kiru");
            //         PreparedStatement st = con.prepareStatement("delete from bio where id='"+jTextField1.getText()+"' ");
            //         st.execute();
              PreparedStatement st1 = con.prepareStatement("select * from Nurse where id = '"+ssid.getText()+"'");
              PreparedStatement st2 = con.prepareStatement("select * from Nurse");
            // st1.setString(1, jTextField1.getText());

               ResultSet rs =st1.executeQuery();
               ssjtable1.setModel(DbUtils.resultSetToTableModel(rs));
               
               ResultSet rs2 =st2.executeQuery();
               ssjtable2.setModel(DbUtils.resultSetToTableModel(rs2));
               
               ssh1.setText("SINGLE RECORD OF NURSE:");
               ssh2.setText("ALL RECORD OF NURSES:");
            //
            //            ddjtable.setModel(DbUtils.resultSetToTableModel(rs));
//               ResultSet rs2 =st1.executeQuery();
//               while(rs2.next()){
//                String id , fn , ln, rd ,ag, bg , gen , pd , e ,co , d , r  ;
//
//                id= rs2.getString(1);
//                fn = rs2.getString(2);
//                ln = rs2.getString(3);
//                rd = rs2.getString(4);
//                ag = rs2.getString(5);
//                bg = rs2.getString(6);
//                gen = rs2.getString(7);
//                pd = rs2.getString(8);
//                e = rs2.getString(9);
//                co = rs2.getString(10);
//                d = rs2.getString(11);
//                r = rs2.getString(12);

             

              }
           
            catch(Exception f){
               System.out.println(f);
            }
        }
        
                if(ssd.getSelectedIndex()==1)
        {
        try{

              Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");

              Connection con = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=Management;username=faisal;password=kiru");
            //         PreparedStatement st = con.prepareStatement("delete from bio where id='"+jTextField1.getText()+"' ");
            //         st.execute();
              PreparedStatement st1 = con.prepareStatement("select * from Ward_Boy where id = '"+ssid.getText()+"'");
              PreparedStatement st2 = con.prepareStatement("select * from Ward_Boy");
            // st1.setString(1, jTextField1.getText());

               ResultSet rs =st1.executeQuery();
               ssjtable1.setModel(DbUtils.resultSetToTableModel(rs));
               
               ResultSet rs2 =st2.executeQuery();
               ssjtable2.setModel(DbUtils.resultSetToTableModel(rs2));
               
               ssh1.setText("SINGLE RECORD OF WARD BOY:");
               ssh2.setText("ALL RECORD OF WARD BOYS:");
                }
           
                catch(Exception f){
                System.out.println(f);
            }
        }
      
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
        this.hide();
        new LoginPage().show();
    }//GEN-LAST:event_jButton5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchStaff().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JComboBox ssd;
    private javax.swing.JLabel ssh1;
    private javax.swing.JLabel ssh2;
    private javax.swing.JTextField ssid;
    private javax.swing.JTable ssjtable1;
    private javax.swing.JTable ssjtable2;
    // End of variables declaration//GEN-END:variables
}
