/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package hospitalmanagement;

import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Faisal
 */
public class UpdateStaff extends javax.swing.JFrame {

    /**
     * Creates new form UpdateStaff
     */
    public UpdateStaff() {
        initComponents();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        sut = new javax.swing.JTextField();
        sud = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        supa = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        sue = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        suc = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        sufn = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        suln = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        sujd = new javax.swing.JTextField();
        pg = new javax.swing.JLabel();
        suage = new javax.swing.JTextField();
        age = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        sui = new javax.swing.JTextField();
        sugen = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        sujtable = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        suid = new javax.swing.JTextField();
        sude = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        subtn = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 153, 255)));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("APPOINT AS A:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("TIMING:");

        sud.setEditable(false);
        sud.setEnabled(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sut, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addComponent(sud))
                .addGap(20, 20, 20))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(sud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(sut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 255)));

        supa.setColumns(20);
        supa.setRows(5);
        jScrollPane1.setViewportView(supa);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("PRESENT ADDRESS");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("EMAIL ADDRESS:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("CONTACT");

        suc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sucActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sue, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(suc, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(suc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("HOSPITAL INFORMATION");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 255));
        jLabel13.setText("CONTACT INFORMATION");

        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 255)));
        jPanel2.setOpaque(false);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("FIRST NAME:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("LAST NAME:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("JOINING DATE:");

        pg.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pg.setText("GENDER:");

        age.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        age.setText("AGE:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("ID:");

        sui.setEditable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel8)
                                .addComponent(age)
                                .addComponent(jLabel3))
                            .addGap(25, 25, 25))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(pg)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(114, 114, 114)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sufn, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(suln, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(suage, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sujd, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sugen)))
                    .addComponent(sui, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(sui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(sufn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(suln, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(sujd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(age)
                    .addComponent(suage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pg)
                    .addComponent(sugen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 255));
        jLabel12.setText("PERSONAL INFORMATION:");

        sujtable.setBackground(new java.awt.Color(51, 102, 255));
        sujtable.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sujtable.setForeground(new java.awt.Color(255, 255, 255));
        sujtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "FIRST NAME", "LAST NAME", "JOINING", "AGE", "GENDER", "PRESENT ADDRESS", "EMAIL ADD", "CONTACT", "DESINATION", "TIMING"
            }
        ));
        jScrollPane2.setViewportView(sujtable);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("SEARCH BY ID:");

        suid.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        sude.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sude.setForeground(new java.awt.Color(0, 102, 255));
        sude.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "NURSE", "WARD BOY" }));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 51, 255));
        jButton2.setText("SEARCH");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        subtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        subtn.setForeground(new java.awt.Color(51, 51, 255));
        subtn.setText("UPDATE");
        subtn.setEnabled(false);
        subtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                subtnMouseClicked(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setFont(new java.awt.Font("Stencil Std", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(51, 51, 255));
        jButton5.setText("Log Out");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(jLabel13)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(92, 269, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(suid, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sude, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(subtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(suid, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sude, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void sucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sucActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sucActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        
        subtn.setEnabled(true);

        if(sude.getSelectedIndex()==0)
        {
            try{

                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");

                Connection con = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=Management;username=faisal;password=kiru");
                //         PreparedStatement st = con.prepareStatement("delete from bio where id='"+jTextField1.getText()+"' ");
                //         st.execute();
                PreparedStatement st1 = con.prepareStatement("select * from Nurse where id = '"+suid.getText()+"'");
                
                // st1.setString(1, jTextField1.getText());

                ResultSet rs =st1.executeQuery();
                sujtable.setModel(DbUtils.resultSetToTableModel(rs));

              
             
                
            // search in fields using normal method
            
            PreparedStatement ps = con.prepareStatement("select * from Nurse where id = ?");
            
            String str = suid.getText();
            ps.setString(1, str);
            
            ResultSet rs2 =ps.executeQuery();
            while(rs2.next()){
                 String i,f,l,jd,ag,g,pa,e,c,des,ti;
                
                i= rs2.getString(1);
                f = rs2.getString(2);
                l = rs2.getString(3);
                jd = rs2.getString(4);
                ag = rs2.getString(5);
                g = rs2.getString(6);
                pa = rs2.getString(7);
                e = rs2.getString(8);
                c = rs2.getString(9);
                des = rs2.getString(10);
                ti = rs2.getString(11);
                
                
                 
                sui.setText(i);
                sufn.setText(f);
                suln.setText(l);
                sujd.setText(jd);
                suage.setText(ag);
                sugen.setText(g);
                supa.setText(pa);
                sue.setText(e);
                suc.setText(c);
                sud.setText(des);
                sut.setText(ti);

        }

                }

                catch(Exception f){
                    System.out.println(f);
                }
            }

            if(sude.getSelectedIndex()==1)
            {
                try{

                    Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");

                    Connection con = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=Management;username=faisal;password=kiru");
                    //         PreparedStatement st = con.prepareStatement("delete from bio where id='"+jTextField1.getText()+"' ");
                    //         st.execute();
                    PreparedStatement st1 = con.prepareStatement("select * from Ward_Boy where id = '"+suid.getText()+"'");
                    PreparedStatement st2 = con.prepareStatement("select * from Ward_Boy");
                    // st1.setString(1, jTextField1.getText());

                    ResultSet rs =st1.executeQuery();
                    sujtable.setModel(DbUtils.resultSetToTableModel(rs));
                    
                         // search in fields using normal method
            
            PreparedStatement ps = con.prepareStatement("select * from Ward_Boy where id = ?");
            
            String str = suid.getText();
            ps.setString(1, str);
            
            ResultSet rs2 =ps.executeQuery();
            while(rs2.next()){
                 String i,f,l,jd,ag,g,pa,e,c,des,ti;
                
                i= rs2.getString(1);
                f = rs2.getString(2);
                l = rs2.getString(3);
                jd = rs2.getString(4);
                ag = rs2.getString(5);
                g = rs2.getString(6);
                pa = rs2.getString(7);
                e = rs2.getString(8);
                c = rs2.getString(9);
                des = rs2.getString(10);
                ti = rs2.getString(11);
                
                
                 
                sui.setText(i);
                sufn.setText(f);
                suln.setText(l);
                sujd.setText(jd);
                suage.setText(ag);
                sugen.setText(g);
                supa.setText(pa);
                sue.setText(e);
                suc.setText(c);
                sud.setText(des);
                sut.setText(ti);

        }

                    

                    
                }

                catch(Exception f){
                    System.out.println(f);
                }
            }

    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void subtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subtnMouseClicked
        // TODO add your handling code here:
        
        if(sude.getSelectedIndex()==0)
        {
        try {
            // TODO add your handling code here:

            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=Management;username=faisal;password=kiru");
            Statement st = con.createStatement();
            String str1 = "UPDATE Nurse SET Id='"+sui.getText()+"' where id='"+suid.getText()+"'";
            String str2 = "UPDATE Nurse SET F_name='"+sufn.getText()+"' where id='"+suid.getText()+"'";
            String str3 = "UPDATE Nurse SET L_name='"+suln.getText()+"' where id='"+suid.getText()+"'";
            String str4 = "UPDATE Nurse SET Join_Date='"+sujd.getText()+"' where id='"+suid.getText()+"'";
            String str5 = "UPDATE Nurse SET Age='"+suage.getText()+"' where id='"+suid.getText()+"'";
          
            String str6 = "UPDATE Nurse SET Gender='"+sugen.getText()+"' where id='"+suid.getText()+"'";
            String str7 = "UPDATE Nurse SET P_Address='"+supa.getText()+"' where id='"+suid.getText()+"'";
            String str8 = "UPDATE Nurse SET Email='"+sue.getText()+"' where id='"+suid.getText()+"'";
            String str9 = "UPDATE Nurse SET Contact='"+suc.getText()+"' where id='"+suid.getText()+"'";
            String str10 = "UPDATE Nurse SET Desination='"+sud.getText()+"' where id='"+suid.getText()+"'";
            String str11 = "UPDATE Nurse SET Timing='"+sut.getText()+"' where id='"+suid.getText()+"'";

            //            String str8 = "UPDATE S_Record SET id='"+dui.getText()+"' where id='"+dsid.getText()+"'";
            st.execute(str1);
            st.execute(str2);
            st.execute(str3);
            st.execute(str4);
            st.execute(str5);
            st.execute(str6);
            st.execute(str7);
            st.execute(str8);
            st.execute(str9);
            st.execute(str10);
            st.execute(str11);
           

            JOptionPane.showMessageDialog(null,"Successfully Insert into Nurse");

            DefaultTableModel dtm = (DefaultTableModel) sujtable.getModel();
            dtm.addRow(new Object[]{sui.getText(),sufn.getText(),suln.getText(),sujd.getText(),suage.getText(),sugen.getText(),supa.getText(),sue.getText(),suc.getText(),sud.getText(),sut.getText()});
        }
        catch(Exception f)
        {
            System.out.println(f);
        }
        }
        
        if(sude.getSelectedIndex()==1)
        {
        try {
            // TODO add your handling code here:

            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=Management;username=faisal;password=kiru");
            Statement st = con.createStatement();
            String str1 = "UPDATE Ward_Boy SET Id='"+sui.getText()+"' where id='"+suid.getText()+"'";
            String str2 = "UPDATE Ward_Boy SET F_name='"+sufn.getText()+"' where id='"+suid.getText()+"'";
            String str3 = "UPDATE Ward_Boy SET L_name='"+suln.getText()+"' where id='"+suid.getText()+"'";
            String str4 = "UPDATE Ward_Boy SET Join_Date='"+sujd.getText()+"' where id='"+suid.getText()+"'";
            String str5 = "UPDATE Ward_Boy SET Age='"+suage.getText()+"' where id='"+suid.getText()+"'";
          
            String str6 = "UPDATE Ward_Boy SET Gender='"+sugen.getText()+"' where id='"+suid.getText()+"'";
            String str7 = "UPDATE Ward_Boy SET P_Address='"+supa.getText()+"' where id='"+suid.getText()+"'";
            String str8 = "UPDATE Ward_Boy SET Email='"+sue.getText()+"' where id='"+suid.getText()+"'";
            String str9 = "UPDATE Ward_Boy SET Contact='"+suc.getText()+"' where id='"+suid.getText()+"'";
            String str10 = "UPDATE Ward_Boy SET Desination='"+sud.getText()+"' where id='"+suid.getText()+"'";
            String str11 = "UPDATE Ward_Boy SET Timing='"+sut.getText()+"' where id='"+suid.getText()+"'";

            //            String str8 = "UPDATE S_Record SET id='"+dui.getText()+"' where id='"+dsid.getText()+"'";
            st.execute(str1);
            st.execute(str2);
            st.execute(str3);
            st.execute(str4);
            st.execute(str5);
            st.execute(str6);
            st.execute(str7);
            st.execute(str8);
            st.execute(str9);
            st.execute(str10);
            st.execute(str11);
           

            JOptionPane.showMessageDialog(null,"Successfully Update into Ward_Boy");

            DefaultTableModel dtm = (DefaultTableModel) sujtable.getModel();
            dtm.addRow(new Object[]{sui.getText(),sufn.getText(),suln.getText(),sujd.getText(),suage.getText(),sugen.getText(),supa.getText(),sue.getText(),suc.getText(),sud.getText(),sut.getText()});
        }
        catch(Exception f)
        {
            System.out.println(f);
        }
        }
    }//GEN-LAST:event_subtnMouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
        this.hide();
        new LoginPage().show();
    }//GEN-LAST:event_jButton5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateStaff().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel age;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel pg;
    private javax.swing.JTextField suage;
    private javax.swing.JButton subtn;
    private javax.swing.JTextField suc;
    private javax.swing.JTextField sud;
    private javax.swing.JComboBox sude;
    private javax.swing.JTextField sue;
    private javax.swing.JTextField sufn;
    private javax.swing.JTextField sugen;
    private javax.swing.JTextField sui;
    private javax.swing.JTextField suid;
    private javax.swing.JTextField sujd;
    private javax.swing.JTable sujtable;
    private javax.swing.JTextField suln;
    private javax.swing.JTextArea supa;
    private javax.swing.JTextField sut;
    // End of variables declaration//GEN-END:variables
}
