/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gym;

/**
 *
 * @author asp
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        fpass = new javax.swing.JLabel();
        sign = new javax.swing.JButton();
        error = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        back = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(445, 513));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Login Id :");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(100, 100, 160, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Password :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(100, 190, 150, 30);

        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        getContentPane().add(name);
        name.setBounds(100, 140, 220, 40);

        jCheckBox1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBox1.setText("Remember My Password");
        getContentPane().add(jCheckBox1);
        jCheckBox1.setBounds(120, 300, 180, 30);

        fpass.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        fpass.setForeground(new java.awt.Color(51, 51, 51));
        fpass.setText("Forgot Password ?");
        getContentPane().add(fpass);
        fpass.setBounds(100, 270, 150, 20);

        sign.setText("Login");
        sign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signActionPerformed(evt);
            }
        });
        sign.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                signKeyPressed(evt);
            }
        });
        getContentPane().add(sign);
        sign.setBounds(150, 350, 120, 30);

        error.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(error);
        error.setBounds(90, 400, 270, 30);
        getContentPane().add(password);
        password.setBounds(100, 230, 220, 40);

        back.setIcon(new javax.swing.ImageIcon("C:\\Users\\Madina\\Documents\\NetBeansProjects\\Gym\\src\\gym\\Login.jpg")); // NOI18N
        getContentPane().add(back);
        back.setBounds(0, 0, 440, 510);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    String log;
    String pass;
    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
       
    }//GEN-LAST:event_jLabel2MouseClicked

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
       
        
        
    }//GEN-LAST:event_nameActionPerformed

    private void signActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signActionPerformed
        
        
        log=name.getText();
        pass=password.getText();
        
        if("admin".equals(log) && "admin".equals(pass))
        {
       Main m=new Main();
       m.show();
       this.dispose();
        }
        
        else
        {
        error.setText("Login id or Password Entered Is wrong.");
        }
        
    }//GEN-LAST:event_signActionPerformed

    private void signKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_signKeyPressed
       log=name.getText();
        pass=password.getText();
        
        if("admin".equals(log) && "admin".equals(pass))
        {
       Login l=new Login();
       l.show();
        }
        
        else
        {
        error.setText("Login id or Password Entered Is wrong.");
        }
    }//GEN-LAST:event_signKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JLabel error;
    private javax.swing.JLabel fpass;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField name;
    private javax.swing.JPasswordField password;
    private javax.swing.JButton sign;
    // End of variables declaration//GEN-END:variables
}
