/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author munim
 */
public class calculator extends javax.swing.JFrame {

    /**
     * Creates new form calculator
     */
    public calculator() {
        initComponents();
        buttonGroup1.add(addradio);
        buttonGroup1.add(subradio);
        buttonGroup1.add(mulradio);
        buttonGroup1.add(divradio);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        num1 = new javax.swing.JTextField();
        num2 = new javax.swing.JTextField();
        plus = new javax.swing.JButton();
        minus = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        multiply = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        quit = new javax.swing.JButton();
        divide = new javax.swing.JButton();
        addradio = new javax.swing.JRadioButton();
        subradio = new javax.swing.JRadioButton();
        mulradio = new javax.swing.JRadioButton();
        divradio = new javax.swing.JRadioButton();
        jComboBox1 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator");
        setResizable(false);
        getContentPane().setLayout(null);

        num1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                num1KeyTyped(evt);
            }
        });
        getContentPane().add(num1);
        num1.setBounds(210, 90, 114, 42);

        num2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num2ActionPerformed(evt);
            }
        });
        num2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                num2KeyTyped(evt);
            }
        });
        getContentPane().add(num2);
        num2.setBounds(50, 90, 114, 43);

        plus.setText("+");
        plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusActionPerformed(evt);
            }
        });
        getContentPane().add(plus);
        plus.setBounds(40, 150, 58, 40);

        minus.setText("-");
        minus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minusActionPerformed(evt);
            }
        });
        getContentPane().add(minus);
        minus.setBounds(120, 150, 58, 42);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(110, 40, 153, 33);

        multiply.setText("*");
        multiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplyActionPerformed(evt);
            }
        });
        getContentPane().add(multiply);
        multiply.setBounds(200, 150, 60, 40);

        clear.setText("CE");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear);
        clear.setBounds(130, 210, 57, 42);

        quit.setText("QUIT");
        quit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitActionPerformed(evt);
            }
        });
        getContentPane().add(quit);
        quit.setBounds(210, 210, 60, 42);

        divide.setText("/");
        divide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divideActionPerformed(evt);
            }
        });
        getContentPane().add(divide);
        divide.setBounds(280, 150, 55, 42);

        addradio.setText("Add");
        addradio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addradioActionPerformed(evt);
            }
        });
        getContentPane().add(addradio);
        addradio.setBounds(10, 270, 50, 23);

        subradio.setText("Subtract");
        subradio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subradioActionPerformed(evt);
            }
        });
        getContentPane().add(subradio);
        subradio.setBounds(60, 270, 80, 23);

        mulradio.setText("Multiply");
        mulradio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mulradioActionPerformed(evt);
            }
        });
        getContentPane().add(mulradio);
        mulradio.setBounds(140, 270, 70, 23);

        divradio.setText("Divide");
        divradio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divradioActionPerformed(evt);
            }
        });
        getContentPane().add(divradio);
        divradio.setBounds(210, 270, 60, 23);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "add", "subtract", "multiply", "divide" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(290, 270, 100, 20);

        setSize(new java.awt.Dimension(416, 338));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void plusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusActionPerformed
        // TODO add your handling code here:
        String number1 = num1.getText();
        String number2 = num2.getText();
        int numm1 = Integer.parseInt(number1);
        int numm2 = Integer.parseInt(number2);
        int num3 = numm1 + numm2;
        jLabel1.setText(String.valueOf(num3));
    }//GEN-LAST:event_plusActionPerformed

    private void multiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplyActionPerformed
        // TODO add your handling code here:
        String number1 = num1.getText();
        String number2 = num2.getText();
        int numm1 = Integer.parseInt(number1);
        int numm2 = Integer.parseInt(number2);
        int num3 = numm1 * numm2;
        jLabel1.setText(String.valueOf(num3));
    }//GEN-LAST:event_multiplyActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        num1.setText(null);
        num2.setText(null); 
        jLabel1.setText(null); 
    }//GEN-LAST:event_clearActionPerformed

    private void quitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitActionPerformed
        // TODO add your handling code here:
        this.hide();
    }//GEN-LAST:event_quitActionPerformed

    private void divideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divideActionPerformed
        // TODO add your handling code here:
//        String number1 = num1.getText();
//        String number2 = num2.getText();
        int numm1 = Integer.parseInt(num1.getText());
        int numm2 = Integer.parseInt(num2.getText());
        float num3 = (float)numm1 / numm2;
        jLabel1.setText(String.valueOf(num3));
    }//GEN-LAST:event_divideActionPerformed

    private void minusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minusActionPerformed
        // TODO add your handling code here:
        String number1 = num1.getText();
        String number2 = num2.getText();
        int numm1 = Integer.parseInt(number1);
        int numm2 = Integer.parseInt(number2);
        int num3 = numm2 - numm1;
        jLabel1.setText(String.valueOf(num3));
    }//GEN-LAST:event_minusActionPerformed

    private void num2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num2ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_num2ActionPerformed

    private void num2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_num2KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!Character.isDigit(c)){
            evt.consume();
        }
    }//GEN-LAST:event_num2KeyTyped

    private void num1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_num1KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!Character.isDigit(c)){
            evt.consume();
        }
    }//GEN-LAST:event_num1KeyTyped

    private void addradioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addradioActionPerformed
        // TODO add your handling code here:
        int numm1 = Integer.parseInt(num1.getText());
        int numm2 = Integer.parseInt(num2.getText());
        int num3 = numm1 + numm2;
        jLabel1.setText(String.valueOf(num3));
    }//GEN-LAST:event_addradioActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        int numm1 = Integer.parseInt(num1.getText());
        int numm2 = Integer.parseInt(num2.getText());
        if(jComboBox1.getSelectedIndex() == 0) {
            int num3 = numm1 + numm2;
            jLabel1.setText(String.valueOf(num3));
        } else if(jComboBox1.getSelectedIndex() == 1) {
            int num3 = numm1 - numm2;
            jLabel1.setText(String.valueOf(num3));
        } else if(jComboBox1.getSelectedItem().equals("multiply")) { 
            int num3 = numm1 * numm2;
            jLabel1.setText(String.valueOf(num3));
        } else if(jComboBox1.getSelectedIndex() == 3) {
            float num3 = (float)numm1 / numm2;
            jLabel1.setText(String.valueOf(num3));
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void subradioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subradioActionPerformed
        // TODO add your handling code here:
        int numm1 = Integer.parseInt(num1.getText());
        int numm2 = Integer.parseInt(num2.getText());
        int num3 = numm1 - numm2;
        jLabel1.setText(String.valueOf(num3));
    }//GEN-LAST:event_subradioActionPerformed

    private void mulradioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mulradioActionPerformed

        int numm1 = Integer.parseInt(num1.getText());
        int numm2 = Integer.parseInt(num2.getText());
        int num3 = numm1 * numm2;
        jLabel1.setText(String.valueOf(num3));
        // TODO add your handling code here:
    }//GEN-LAST:event_mulradioActionPerformed

    private void divradioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divradioActionPerformed
        // TODO add your handling code here:
        int numm1 = Integer.parseInt(num1.getText());
        int numm2 = Integer.parseInt(num2.getText());
        int num3 = numm1 / numm2;
        jLabel1.setText(String.valueOf(num3));
    }//GEN-LAST:event_divradioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton addradio;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton clear;
    private javax.swing.JButton divide;
    private javax.swing.JRadioButton divradio;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton minus;
    private javax.swing.JRadioButton mulradio;
    private javax.swing.JButton multiply;
    private javax.swing.JTextField num1;
    private javax.swing.JTextField num2;
    private javax.swing.JButton plus;
    private javax.swing.JButton quit;
    private javax.swing.JRadioButton subradio;
    // End of variables declaration//GEN-END:variables
}
