/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author munim
 */
public class MyCalculator extends javax.swing.JFrame {

    /**
     * Creates new form MyCalculator
     */
   
    double firstnum;
    double secondnum;
    double result;
    String operator;
    
    public MyCalculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtDisplay = new javax.swing.JTextField();
        Btn1 = new javax.swing.JButton();
        Btn2 = new javax.swing.JButton();
        Btn3 = new javax.swing.JButton();
        Btn4 = new javax.swing.JButton();
        Btn5 = new javax.swing.JButton();
        Btn6 = new javax.swing.JButton();
        Btn7 = new javax.swing.JButton();
        Btn8 = new javax.swing.JButton();
        Btn9 = new javax.swing.JButton();
        Btn0 = new javax.swing.JButton();
        BtnDot = new javax.swing.JButton();
        BtnMultiply = new javax.swing.JButton();
        BtnDivide = new javax.swing.JButton();
        BtnMinus = new javax.swing.JButton();
        BtnAdd = new javax.swing.JButton();
        BtnEqual = new javax.swing.JButton();
        BtnBack = new javax.swing.JButton();
        BtnClearAll = new javax.swing.JButton();
        BtnClear = new javax.swing.JButton();
        BtnSign = new javax.swing.JButton();
        BtnPow = new javax.swing.JButton();
        BtnSq = new javax.swing.JButton();
        BtnSqrt = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator");
        setResizable(false);
        getContentPane().setLayout(null);

        txtDisplay.setEditable(false);
        txtDisplay.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtDisplay.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(txtDisplay);
        txtDisplay.setBounds(10, 11, 258, 51);

        Btn1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Btn1.setText("1");
        Btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn1ActionPerformed(evt);
            }
        });
        getContentPane().add(Btn1);
        Btn1.setBounds(10, 121, 44, 43);

        Btn2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Btn2.setText("2");
        Btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn2ActionPerformed(evt);
            }
        });
        getContentPane().add(Btn2);
        Btn2.setBounds(60, 121, 44, 43);

        Btn3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Btn3.setText("3");
        Btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn3ActionPerformed(evt);
            }
        });
        getContentPane().add(Btn3);
        Btn3.setBounds(110, 121, 44, 43);

        Btn4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Btn4.setText("4");
        Btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn4ActionPerformed(evt);
            }
        });
        getContentPane().add(Btn4);
        Btn4.setBounds(10, 170, 44, 43);

        Btn5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Btn5.setText("5");
        Btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn5ActionPerformed(evt);
            }
        });
        getContentPane().add(Btn5);
        Btn5.setBounds(60, 170, 44, 43);

        Btn6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Btn6.setText("6");
        Btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn6ActionPerformed(evt);
            }
        });
        getContentPane().add(Btn6);
        Btn6.setBounds(110, 170, 44, 43);

        Btn7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Btn7.setText("7");
        Btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn7ActionPerformed(evt);
            }
        });
        getContentPane().add(Btn7);
        Btn7.setBounds(10, 219, 44, 43);

        Btn8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Btn8.setText("8");
        Btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn8ActionPerformed(evt);
            }
        });
        getContentPane().add(Btn8);
        Btn8.setBounds(60, 219, 44, 43);

        Btn9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Btn9.setText("9");
        Btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn9ActionPerformed(evt);
            }
        });
        getContentPane().add(Btn9);
        Btn9.setBounds(110, 219, 45, 43);

        Btn0.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Btn0.setText("0");
        Btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn0ActionPerformed(evt);
            }
        });
        getContentPane().add(Btn0);
        Btn0.setBounds(60, 270, 44, 43);

        BtnDot.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnDot.setText(".");
        BtnDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDotActionPerformed(evt);
            }
        });
        getContentPane().add(BtnDot);
        BtnDot.setBounds(110, 270, 44, 43);

        BtnMultiply.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnMultiply.setText("*");
        BtnMultiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMultiplyActionPerformed(evt);
            }
        });
        getContentPane().add(BtnMultiply);
        BtnMultiply.setBounds(161, 219, 44, 43);

        BtnDivide.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnDivide.setText("/");
        BtnDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDivideActionPerformed(evt);
            }
        });
        getContentPane().add(BtnDivide);
        BtnDivide.setBounds(161, 268, 44, 43);

        BtnMinus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnMinus.setText("-");
        BtnMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMinusActionPerformed(evt);
            }
        });
        getContentPane().add(BtnMinus);
        BtnMinus.setBounds(160, 170, 44, 43);

        BtnAdd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnAdd.setText("+");
        BtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAddActionPerformed(evt);
            }
        });
        getContentPane().add(BtnAdd);
        BtnAdd.setBounds(160, 121, 44, 43);

        BtnEqual.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnEqual.setText("=");
        BtnEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEqualActionPerformed(evt);
            }
        });
        getContentPane().add(BtnEqual);
        BtnEqual.setBounds(213, 219, 53, 92);

        BtnBack.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnBack.setText("BK");
        BtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBackActionPerformed(evt);
            }
        });
        getContentPane().add(BtnBack);
        BtnBack.setBounds(67, 72, 60, 43);

        BtnClearAll.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnClearAll.setText("C");
        BtnClearAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnClearAllActionPerformed(evt);
            }
        });
        getContentPane().add(BtnClearAll);
        BtnClearAll.setBounds(10, 270, 44, 43);

        BtnClear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnClear.setText("CE");
        BtnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnClearActionPerformed(evt);
            }
        });
        getContentPane().add(BtnClear);
        BtnClear.setBounds(133, 72, 64, 43);

        BtnSign.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnSign.setText("+/-");
        BtnSign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSignActionPerformed(evt);
            }
        });
        getContentPane().add(BtnSign);
        BtnSign.setBounds(203, 72, 63, 43);

        BtnPow.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnPow.setText("^");
        BtnPow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPowActionPerformed(evt);
            }
        });
        getContentPane().add(BtnPow);
        BtnPow.setBounds(213, 121, 53, 43);

        BtnSq.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnSq.setText("^2");
        BtnSq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSqActionPerformed(evt);
            }
        });
        getContentPane().add(BtnSq);
        BtnSq.setBounds(213, 170, 53, 43);

        BtnSqrt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnSqrt.setText("sq");
        BtnSqrt.setToolTipText("");
        BtnSqrt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnSqrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSqrtActionPerformed(evt);
            }
        });
        getContentPane().add(BtnSqrt);
        BtnSqrt.setBounds(10, 70, 50, 43);

        jMenu1.setText("View");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("Standard");
        jMenu1.add(jRadioButtonMenuItem1);

        jMenuItem2.setText("Scientific");
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(293, 385));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnClearActionPerformed
        // TODO add your handling code here:
        txtDisplay.setText(null); 
    }//GEN-LAST:event_BtnClearActionPerformed

    private void Btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn1ActionPerformed
        // TODO add your handling code here:
        String number = txtDisplay.getText() + Btn1.getText();
        txtDisplay.setText(number); 
    }//GEN-LAST:event_Btn1ActionPerformed

    private void Btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn2ActionPerformed
        // TODO add your handling code here:
        String number = txtDisplay.getText() + Btn2.getText();
        txtDisplay.setText(number);
    }//GEN-LAST:event_Btn2ActionPerformed

    private void Btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn3ActionPerformed
        // TODO add your handling code here:
        String number = txtDisplay.getText() + Btn3.getText();
        txtDisplay.setText(number);
    }//GEN-LAST:event_Btn3ActionPerformed

    private void Btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn4ActionPerformed
        // TODO add your handling code here:
        String number = txtDisplay.getText() + Btn4.getText();
        txtDisplay.setText(number);
    }//GEN-LAST:event_Btn4ActionPerformed

    private void Btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn5ActionPerformed
        // TODO add your handling code here:
        String number = txtDisplay.getText() + Btn5.getText();
        txtDisplay.setText(number);
    }//GEN-LAST:event_Btn5ActionPerformed

    private void Btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn6ActionPerformed
        // TODO add your handling code here:
        String number = txtDisplay.getText() + Btn6.getText();
        txtDisplay.setText(number);
    }//GEN-LAST:event_Btn6ActionPerformed

    private void Btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn7ActionPerformed
        // TODO add your handling code here:
        String number = txtDisplay.getText() + Btn7.getText();
        txtDisplay.setText(number);
    }//GEN-LAST:event_Btn7ActionPerformed

    private void Btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn8ActionPerformed
        // TODO add your handling code here:
        String number = txtDisplay.getText() + Btn8.getText();
        txtDisplay.setText(number);
    }//GEN-LAST:event_Btn8ActionPerformed

    private void Btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn9ActionPerformed
        // TODO add your handling code here:
        String number = txtDisplay.getText() + Btn9.getText();
        txtDisplay.setText(number);
    }//GEN-LAST:event_Btn9ActionPerformed

    private void Btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn0ActionPerformed
        // TODO add your handling code here:
        if(txtDisplay.getText().length() < 1){
        //    txtDisplay.setText("0"); 
        } else {
            String number = txtDisplay.getText() + Btn0.getText();
            txtDisplay.setText(number);
        }
        
    }//GEN-LAST:event_Btn0ActionPerformed

    private void BtnClearAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnClearAllActionPerformed
        // TODO add your handling code here:
        txtDisplay.setText(null);
        firstnum = 0;
        secondnum = 0;
        result = 0;
        operator = null;
    }//GEN-LAST:event_BtnClearAllActionPerformed

    private void BtnDotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDotActionPerformed
        // TODO add your handling code here:
        if(!txtDisplay.getText().contains(".")){
            String number = txtDisplay.getText() + BtnDot.getText();
            txtDisplay.setText(number);
        }
    }//GEN-LAST:event_BtnDotActionPerformed

    private void BtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAddActionPerformed
        // TODO add your handling code here:
        firstnum = Double.parseDouble(txtDisplay.getText());
        operator = "+";
        txtDisplay.setText(null); 
    }//GEN-LAST:event_BtnAddActionPerformed

    private void BtnMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMinusActionPerformed
        // TODO add your handling code here:
        firstnum = Double.parseDouble(txtDisplay.getText());
        operator = "-";
        txtDisplay.setText(null); 
    }//GEN-LAST:event_BtnMinusActionPerformed

    private void BtnMultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMultiplyActionPerformed
        // TODO add your handling code here:
        firstnum = Double.parseDouble(txtDisplay.getText());
        operator = "*";
        txtDisplay.setText(null); 
    }//GEN-LAST:event_BtnMultiplyActionPerformed

    private void BtnDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDivideActionPerformed
        // TODO add your handling code here:
        firstnum = Double.parseDouble(txtDisplay.getText());
        operator = "/";
        txtDisplay.setText(null); 
    }//GEN-LAST:event_BtnDivideActionPerformed

    private void BtnEqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEqualActionPerformed
        // TODO add your handling code here:
        secondnum = Double.parseDouble(txtDisplay.getText());
        
        if(operator.equals("+")){
            result = firstnum + secondnum;
        } else if(operator.equals("-")){
            result = firstnum - secondnum;
        } else if(operator.equals("*")){
            result = firstnum * secondnum;
        } else if(operator.equals("/")){
            result = firstnum / secondnum;
        } else if(operator.equals("power")){
            result = Math.pow(firstnum, secondnum);
        }
        
        txtDisplay.setText(String.valueOf(result));
    }//GEN-LAST:event_BtnEqualActionPerformed

    private void BtnSignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSignActionPerformed
        // TODO add your handling code here:
        double temp = Double.parseDouble(txtDisplay.getText());
        temp *= (-1);
        txtDisplay.setText(String.valueOf(temp)); 
    }//GEN-LAST:event_BtnSignActionPerformed

    private void BtnPowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPowActionPerformed
        // TODO add your handling code here:
        firstnum = Double.parseDouble(txtDisplay.getText());
        operator = "power";
        txtDisplay.setText(null);
    }//GEN-LAST:event_BtnPowActionPerformed

    private void BtnSqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSqActionPerformed
        // TODO add your handling code here:
        firstnum = Double.parseDouble(txtDisplay.getText());
        double answer = Math.pow(firstnum, 2);
        txtDisplay.setText(String.valueOf(answer));
    }//GEN-LAST:event_BtnSqActionPerformed

    private void BtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBackActionPerformed
        // TODO add your handling code here:
        int temper = Integer.parseInt(txtDisplay.getText());
        temper = temper / 10;
        txtDisplay.setText(String.valueOf(temper)); 
    }//GEN-LAST:event_BtnBackActionPerformed

    private void BtnSqrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSqrtActionPerformed
        // TODO add your handling code here:
        double root = Double.parseDouble(txtDisplay.getText());
        txtDisplay.setText(String.valueOf(Math.sqrt(root)));
    }//GEN-LAST:event_BtnSqrtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyCalculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn0;
    private javax.swing.JButton Btn1;
    private javax.swing.JButton Btn2;
    private javax.swing.JButton Btn3;
    private javax.swing.JButton Btn4;
    private javax.swing.JButton Btn5;
    private javax.swing.JButton Btn6;
    private javax.swing.JButton Btn7;
    private javax.swing.JButton Btn8;
    private javax.swing.JButton Btn9;
    private javax.swing.JButton BtnAdd;
    private javax.swing.JButton BtnBack;
    private javax.swing.JButton BtnClear;
    private javax.swing.JButton BtnClearAll;
    private javax.swing.JButton BtnDivide;
    private javax.swing.JButton BtnDot;
    private javax.swing.JButton BtnEqual;
    private javax.swing.JButton BtnMinus;
    private javax.swing.JButton BtnMultiply;
    private javax.swing.JButton BtnPow;
    private javax.swing.JButton BtnSign;
    private javax.swing.JButton BtnSq;
    private javax.swing.JButton BtnSqrt;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JTextField txtDisplay;
    // End of variables declaration//GEN-END:variables
}
