/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gym;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Madina
 */
public class Instructorview extends javax.swing.JFrame {

      Vector<String> header=new Vector<String>();
    Vector<Vector<String>> data=new Vector<Vector<String>>();
    
    /**
     * Creates new form Instructorview
     */
    public Instructorview() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        instable = new javax.swing.JTable();
        txt1 = new javax.swing.JTextField();
        txt2 = new javax.swing.JTextField();
        txt3 = new javax.swing.JTextField();
        txt4 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt5 = new javax.swing.JTextArea();
        txt6 = new javax.swing.JTextField();
        txt7 = new javax.swing.JTextField();
        txt8 = new javax.swing.JTextField();
        modify = new javax.swing.JButton();
        remove = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Instructorview = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        msoption = new javax.swing.JMenuItem();
        addmember = new javax.swing.JMenuItem();
        viewmember = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        addplan = new javax.swing.JMenuItem();
        viewplan = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        addinstructor = new javax.swing.JMenuItem();
        viewinstructor = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        addequipment = new javax.swing.JMenuItem();
        viewequipment = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        transaction = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        jMenu11 = new javax.swing.JMenu();
        contents = new javax.swing.JMenuItem();
        aboutus = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1370, 735));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Instuctor View");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(610, 10, 330, 40);

        jButton1.setText("View Record");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(700, 640, 140, 30);

        instable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                instableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(instable);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(340, 60, 870, 560);
        getContentPane().add(txt1);
        txt1.setBounds(140, 90, 170, 30);
        getContentPane().add(txt2);
        txt2.setBounds(140, 140, 170, 30);

        txt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt3ActionPerformed(evt);
            }
        });
        getContentPane().add(txt3);
        txt3.setBounds(140, 190, 170, 30);
        getContentPane().add(txt4);
        txt4.setBounds(140, 240, 170, 30);

        txt5.setColumns(20);
        txt5.setRows(5);
        jScrollPane2.setViewportView(txt5);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(140, 280, 170, 96);

        txt6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt6ActionPerformed(evt);
            }
        });
        getContentPane().add(txt6);
        txt6.setBounds(140, 390, 170, 30);
        getContentPane().add(txt7);
        txt7.setBounds(140, 440, 170, 30);

        txt8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt8ActionPerformed(evt);
            }
        });
        getContentPane().add(txt8);
        txt8.setBounds(140, 490, 170, 30);

        modify.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        modify.setText("Modify");
        modify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyActionPerformed(evt);
            }
        });
        getContentPane().add(modify);
        modify.setBounds(120, 540, 90, 30);

        remove.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        remove.setText("Remove");
        remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeActionPerformed(evt);
            }
        });
        getContentPane().add(remove);
        remove.setBounds(230, 540, 90, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Instructor_Id");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 94, 110, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("First_Name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 144, 110, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Last_Name");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 194, 100, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Contact_No");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 244, 100, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Address");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 320, 100, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Date OF Join");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 390, 120, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Schedule");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(20, 440, 110, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Amount");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(20, 494, 100, 20);

        Instructorview.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gym/Images/Background.jpg"))); // NOI18N
        getContentPane().add(Instructorview);
        Instructorview.setBounds(0, 0, 1370, 700);

        jMenuBar1.setPreferredSize(new java.awt.Dimension(466, 28));

        jMenu1.setText("Home");

        jMenuItem1.setText("Quit/Exit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu5.setText("Membership");

        msoption.setText("Membership Options");
        msoption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msoptionActionPerformed(evt);
            }
        });
        jMenu5.add(msoption);

        addmember.setText("Add Member");
        addmember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addmemberActionPerformed(evt);
            }
        });
        jMenu5.add(addmember);

        viewmember.setText("View All");
        viewmember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewmemberActionPerformed(evt);
            }
        });
        jMenu5.add(viewmember);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("Plan/Course");

        addplan.setText("Add");
        addplan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addplanActionPerformed(evt);
            }
        });
        jMenu6.add(addplan);

        viewplan.setText("View All");
        viewplan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewplanActionPerformed(evt);
            }
        });
        jMenu6.add(viewplan);

        jMenuBar1.add(jMenu6);

        jMenu7.setText("Instructor");

        addinstructor.setText("Add");
        addinstructor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addinstructorActionPerformed(evt);
            }
        });
        jMenu7.add(addinstructor);

        viewinstructor.setText("View All");
        viewinstructor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewinstructorActionPerformed(evt);
            }
        });
        jMenu7.add(viewinstructor);

        jMenuBar1.add(jMenu7);

        jMenu8.setText("Equipment");

        addequipment.setText("Add");
        addequipment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addequipmentActionPerformed(evt);
            }
        });
        jMenu8.add(addequipment);

        viewequipment.setText("View All");
        viewequipment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewequipmentActionPerformed(evt);
            }
        });
        jMenu8.add(viewequipment);

        jMenuBar1.add(jMenu8);

        jMenu9.setText("Transaction");

        transaction.setText("Membership Fees");
        transaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transactionActionPerformed(evt);
            }
        });
        jMenu9.add(transaction);

        jMenuBar1.add(jMenu9);

        jMenu10.setText("History");
        jMenu10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu10MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu10);

        jMenu11.setText("Help");

        contents.setText("Contents");
        contents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contentsActionPerformed(evt);
            }
        });
        jMenu11.add(contents);

        aboutus.setText("About us");
        aboutus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutusActionPerformed(evt);
            }
        });
        jMenu11.add(aboutus);

        jMenuBar1.add(jMenu11);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.hide();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void msoptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msoptionActionPerformed
        msoption msdetail=new msoption();
        msdetail.show();
        this.hide();
    }//GEN-LAST:event_msoptionActionPerformed

    private void addmemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addmemberActionPerformed
        Membership addmem=new Membership();
        addmem.show();
        this.hide();
    }//GEN-LAST:event_addmemberActionPerformed

    private void viewmemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewmemberActionPerformed
        Memberview mview=new Memberview();
        mview.show();
        this.hide();
    }//GEN-LAST:event_viewmemberActionPerformed

    private void addplanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addplanActionPerformed
        plancourse addpplan=new plancourse();
        addpplan.show();
        this.hide();
    }//GEN-LAST:event_addplanActionPerformed

    private void viewplanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewplanActionPerformed
        Planview pview=new Planview();
        pview.show();
        this.hide();
    }//GEN-LAST:event_viewplanActionPerformed

    private void addinstructorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addinstructorActionPerformed
        Instructor addins=new Instructor();
        addins.show();
        this.hide();

    }//GEN-LAST:event_addinstructorActionPerformed

    private void viewinstructorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewinstructorActionPerformed
        Instructorview viewins=new Instructorview();
        viewins.show();
        this.hide();
    }//GEN-LAST:event_viewinstructorActionPerformed

    private void addequipmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addequipmentActionPerformed
        Equipment addequi=new Equipment();
        addequi.show();
        this.hide();
    }//GEN-LAST:event_addequipmentActionPerformed

    private void viewequipmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewequipmentActionPerformed
        Equipmentview viewequip=new Equipmentview();
        viewequip.show();
        this.hide();
    }//GEN-LAST:event_viewequipmentActionPerformed

    private void transactionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transactionActionPerformed
        Transaction trans=new Transaction();
        trans.show();
        this.hide();
    }//GEN-LAST:event_transactionActionPerformed

    private void jMenu10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu10MouseClicked
        History hist=new History();
        hist.show();
        this.hide();
    }//GEN-LAST:event_jMenu10MouseClicked

    private void contentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contentsActionPerformed
        Contents cont=new Contents();
        cont.show();
        this.hide();
    }//GEN-LAST:event_contentsActionPerformed

    private void aboutusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutusActionPerformed
        About about=new About();
        about.show();
        this.hide();
    }//GEN-LAST:event_aboutusActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         header.clear();
        data.clear();
        
        try
        {
                
        Connection con=DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=city_gym;username=sa;password=aptech");
        Statement s=con.createStatement();
        
        String query="select * from instructor";
        ResultSet res=s.executeQuery(query);
        while(res.next())
        {
        String inst_id=res.getString(1);
        String fname=res.getString(2);
        String lname=res.getString(3);
        String c_no=res.getString(4);
        String adres=res.getString(5);
        String doj=res.getString(6);
        String schedule=res.getString(7);
        String sallary=res.getString(8);
            
        Vector<String> row=new Vector<String>();
        
        row.add(inst_id);
        row.add(fname);
        row.add(lname);
        row.add(c_no);
        row.add(adres);
        row.add(doj);
        row.add(schedule);
        row.add(sallary);

        data.add(row);
        
        }
      header.add("Instructor Id"); 
      header.add("First Name");
      header.add("Last Name");
      header.add("Contact No"); 
      header.add("Address");
      header.add("Date Of Joining");
      header.add("Schedule");
      header.add("Sallary");
      
      
      instable.setModel(new DefaultTableModel(data,header));
       
        
        
        
        }
        
            catch(Exception e)
            
            {
                System.out.println(e);
            }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void instableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_instableMouseClicked

 
try
{
int row = instable.getSelectedRow();
String inst_id=(instable.getModel().getValueAt(row, 0)).toString();
txt1.setText(inst_id);


String fname=(instable.getModel().getValueAt(row, 1)).toString();
txt2.setText(fname);

String lname=(instable.getModel().getValueAt(row, 2)).toString();
txt3.setText(lname);

String c_no=(instable.getModel().getValueAt(row, 3)).toString();
txt4.setText(c_no);

String adres=(instable.getModel().getValueAt(row, 5)).toString();
txt6.setText(adres);

String doj=(instable.getModel().getValueAt(row, 4)).toString();
txt5.setText(doj);

String schedule=(instable.getModel().getValueAt(row, 6)).toString();
txt7.setText(schedule);


String sallary=(instable.getModel().getValueAt(row, 7)).toString();
txt8.setText(sallary);


}
    catch(Exception e)
            {
                System.out.println(e);
            }
        


    }//GEN-LAST:event_instableMouseClicked

    private void modifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyActionPerformed

        try
        {

            Connection con=DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=city_gym;username=sa;password=aptech");
            Statement s=con.createStatement();

            String inst_id=txt1.getText();
            String fname=txt2.getText();
            String lname=txt3.getText();
            String c_no=txt4.getText();
            String doj=txt5.getText();
            String adres=txt6.getText();
            String schedule=txt7.getText();
            String sallary=txt8.getText();

            String msg="Record Updated";

            s.execute("update instructor set fname='"+fname+"' where inst_id='"+inst_id+"' " );
            JOptionPane.showMessageDialog(rootPane, msg);

        }

        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_modifyActionPerformed

    private void removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeActionPerformed

        try
        {

            Connection con=DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=city_gym;username=sa;password=aptech");
            Statement s=con.createStatement();

            String inst_id=txt1.getText();
            String fname=txt2.getText();
            String lname=txt3.getText();
            String c_no=txt4.getText();
            String doj=txt5.getText();
            String adres=txt6.getText();
            String schedule=txt7.getText();
            String sallary=txt8.getText();

            String msg="Record Deleted";

            s.execute("delete from instructor where inst_id=('"+inst_id+"')");
            JOptionPane.showMessageDialog(rootPane, msg);

        }

        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_removeActionPerformed

    private void txt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt3ActionPerformed

    private void txt6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt6ActionPerformed

    private void txt8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Instructorview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Instructorview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Instructorview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Instructorview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Instructorview().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Instructorview;
    private javax.swing.JMenuItem aboutus;
    private javax.swing.JMenuItem addequipment;
    private javax.swing.JMenuItem addinstructor;
    private javax.swing.JMenuItem addmember;
    private javax.swing.JMenuItem addplan;
    private javax.swing.JMenuItem contents;
    private javax.swing.JTable instable;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton modify;
    private javax.swing.JMenuItem msoption;
    private javax.swing.JButton remove;
    private javax.swing.JMenuItem transaction;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt2;
    private javax.swing.JTextField txt3;
    private javax.swing.JTextField txt4;
    private javax.swing.JTextArea txt5;
    private javax.swing.JTextField txt6;
    private javax.swing.JTextField txt7;
    private javax.swing.JTextField txt8;
    private javax.swing.JMenuItem viewequipment;
    private javax.swing.JMenuItem viewinstructor;
    private javax.swing.JMenuItem viewmember;
    private javax.swing.JMenuItem viewplan;
    // End of variables declaration//GEN-END:variables
}
